/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("com.company.kotlin-application-conventions")
}

application {
    // Define the main class for the application.
    mainClass.set("com.company.app.AppKt")
}
